/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	F:/al/sf1_-project-master/sf1_-project-master/src/PWM/td_project/al_ip/rom_weight.v
 ** Date	:	2023 11 12
 ** TD version	:	5.6.59063
\************************************************************/

`timescale 1ns / 1ps

module rom_weight ( doa, addra, clka, rsta );

	output [7:0] doa;

	input  [8:0] addra;
	input  clka;
	input  rsta;




	SF1_LOGIC_BRAM #( .DATA_WIDTH_A(8),
				.ADDR_WIDTH_A(9),
				.DATA_DEPTH_A(480),
				.DATA_WIDTH_B(8),
				.ADDR_WIDTH_B(9),
				.DATA_DEPTH_B(480),
				.MODE("SP"),
				.REGMODE_A("NOREG"),
				.IMPLEMENT("9K"),
				.DEBUGGABLE("NO"),
				.PACKABLE("NO"),
				.INIT_FILE("weight.mif"),
				.FILL_ALL("NONE"))
			inst(
				.dia({8{1'b0}}),
				.dib({8{1'b0}}),
				.addra(addra),
				.addrb({9{1'b0}}),
				.cea(1'b1),
				.ceb(1'b0),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(1'b0),
				.wea(1'b0),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(1'b0),
				.doa(doa),
				.dob());


endmodule